Laba5
AnastasiyaCad/mp2-lab5-Polinom pull request #1
Opened 2018-12-16 21:30 UTC by AnastasiyaCad

2018-12-17 19:46 UTC, alvls requested changes

2018-12-17 19:46 UTC, alvls commented on nn/base_test/test_TPolinom.cpp
> +	TPolinom mypl2("x2+y3+z"), mypl1("3x2+y2+z"), mypl3("4x2+2y2+2z"), sum;
Неверная сумма в mypl3. Непонятно, как у вас тест "проходит"

2018-12-17 19:46 UTC, alvls commented on nn/base_test/test_TPolinom.cpp
> +	TPolinom mypl2("x2+y3+z"), mypl1("3x2+2y2+4z"), mypl3("2x2+3y2+3z"), sum;
Неверная разность в mypl3. Непонятно, как у вас тест "проходит"

2018-12-17 20:06 UTC, AnastasiyaCad commented
Можете подсказать, что за ошибка abort() ?


С уважением, студентка 2 курса ИИТММ (группа 381703-2) Неробова Анастасия
null

2018-12-17 20:10 UTC, alvls commented
Что ж вы сегодня не пришли в т.к.?
Приходите в среду, посмотрим очно.

2018-12-17 20:12 UTC, AnastasiyaCad commented
хорошо. А вообще в каких случаях может возникнуть такая ошибка? 17.12.2018, 23:10, "Alexander Sysoyev" <notifications@github.com>:Что ж вы сегодня не пришли в т.к.?
Приходите в среду, посмотрим очно.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- С уважением, студентка 2 курса ИИТММ (группа 381703-2) Неробова Анастасия

2018-12-17 20:18 UTC, alvls commented
чаще всего неверная работа с памятью
может быть необработанное исключение

2018-12-19 21:10 UTC, merged

2018-12-19 21:17 UTC, alvls commented
Зачем вы сделали merge? Откройте пулл-реквест заново